version: '3'

networks:
  shared-network:

services:

  lefty:
    build: .
    environment:
      - "JAEGER_ENDPOINT=http://jaeger:14268/api/traces"
      - "JAEGER_SERVICE_NAME=Lefty"
    network_mode: host
    command: /app/bin/Debug/netcoreapp3.1/grpc-test --urls=http://localhost:5001

  righty:
    build: .
    environment:
      - "JAEGER_ENDPOINT=http://jaeger:14268/api/traces"
      - "JAEGER_SERVICE_NAME=Righty"
    network_mode: host
    command: /app/bin/Debug/netcoreapp3.1/grpc-test --urls=http://localhost:5002

  pinger:
    build: .
    environment:
      - "TARGET_A=localhost:5001"
      - "TARGET_B=localhost:5002"
    network_mode: host
    command: /app/bin/Debug/netcoreapp3.1/grpc-test ping

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
    networks:
      - shared-network
